version: '2'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:11.0.3
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    restart: always

